### ISSUE TITLE
Creeping article tags for XML Databases section

### ISSUE THREAD

**Issue by kubarium** [edlich/nosql-database.org#18]
Looking at the HTML tags of this page, I can see that there are sections that start with an h2 tag that defines a group of databases. 

    <section>
	<h2 id="multimodel">Multimodel Databases</h2>
	<article>...</article>
	<article>...</article>
	</section>

For XML Databases, the article tags that are supposed to be inside its section are outside and we have a bunch of article tags until the next section.

![XML Databases](http://s29.postimg.org/4qq9d5exz/XML_Databases.gif)

**Comment by edlich** [comment]
Cool. Will fix this. Thanks! Luckily this can't be seen ;-)

**Comment by kubarium** [comment]
I think it doesn't matter for the browser to render it properly but I needed the structure and data. I think I've seen one more case like this in a different node but I'll create another "issue" for that. Thank you for looking into this.

**Comment by edlich** [comment]
can you make a pull request for the next one?
thx!
I fixed this one with a baby on the arm ;-)

**Comment by kubarium** [comment]
Thank you! I'll pay attention to pull request.
